#!/bin/sh
#
#	check_paths - Make sure mush.config paths are valid.
#		      Assumes mush.config has already been loaded in
#		      this shell.
#
if [ -z "$BIN" -o ! -d "$BIN" -o ! -r "$BIN" ]; then
	echo "Error: Invalid BIN directory in mush.config"
	exit 1
fi
if [ -z "$TEXT" -o ! -d "$TEXT" -o ! -w "$TEXT" ]; then
	echo "Error: Invalid TEXT directory in mush.config"
	exit 1
fi
if [ -z "$DATA" -o ! -d "$DATA" -o ! -w "$DATA" ]; then
	echo "Error: Invalid DATA directory in mush.config"
	exit 1
fi
if [ -z "$BACKUP" -o ! -d "$BACKUP" -o ! -w "$BACKUP" ]; then
	echo "Warning: Invalid BACKUP_DIR in mush.config; using . instead"
	BACKUP_DIR=.
fi
