/* src/config.h.  Generated from config.h.in by configure.  */

/**
 * @file config.h
 * @author TinyMUSH development team (https://github.com/TinyMUSH)
 * @brief Configuration options set by configure script
 * @version 4.0
 * @date 2023-11-26
 * 
 * @copyright Copyright (C) 1989-2023 TinyMUSH development team.
 *            You may distribute under the terms the Artistic License,
 *            as specified in the COPYING file.
 * 
 * @note Do not edit this file by hand -- Your changes will be overwritten
 * 
 */

#ifndef __CONFIG_H
#define __CONFIG_H

/* Maximum length of a delimiter */
#define MAX_DELIM_LEN 128

/* max # of iter levels */
#define MAX_ITER_NESTING 1024

/* Number of env vars (%0 et al) */
#define NUM_ENV_VARS 10

/* Name of package */
#define PACKAGE "tinymush"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "https://github.com/TinyMUSH/TinyMUSH/issues"

/* Copyright Notice */
#define PACKAGE_COPYRIGHT "Copyright (C) 1989-2023 TinyMUSH development team."

/* Define to the full name of this package. */
#define PACKAGE_NAME "TinyMUSH"

/* Date of Release */
#define PACKAGE_RELEASE_DATE "2023-11-25"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "TinyMUSH 4.0.0.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "tinymush"

/* Define to the home page for this package. */
#define PACKAGE_URL "https://github.com/TinyMUSH/"

/* Define to the version of this package. */
#define PACKAGE_VERSION "4.0.0.0"

#endif /* __CONFIG_H */
