/**
 * @file defaults.h
 * @author TinyMUSH development team (https://github.com/TinyMUSH)
 * @brief Configuration options set by configure script
 * @version 4.0
 * @date 2023-11-26
 * 
 * @copyright Copyright (C) 1989-2023 TinyMUSH development team.
 *            You may distribute under the terms the Artistic License,
 *            as specified in the COPYING file.
 * 
 * @note Do not edit this file by hand -- Your changes will be overwritten
 * 
 */

#ifndef __DEFAULTS_H
#define __DEFAULTS_H

#define DEFAULT_SHORTNAME "netmush"

#define DEFAULT_BACKUP_UTIL "/usr/bin/tar"
#define DEFAULT_BACKUP_COMPRESS "czvf"
#define DEFAULT_BACKUP_EXTRACT "xzvf"
#define DEFAULT_BACKUP_EXT "tbz"

#define DEFAULT_BACKUP_HOME "/home/eddy/src/TinyMUSH-CMake/game/backups"
#define DEFAULT_BINARY_HOME "/home/eddy/src/TinyMUSH-CMake/game"
#define DEFAULT_CONFIG_FILE "/home/eddy/src/TinyMUSH-CMake/game/configs/netmush.conf"
#define DEFAULT_CONFIG_HOME "/home/eddy/src/TinyMUSH-CMake/game/configs"
#define DEFAULT_DATABASE_HOME "/home/eddy/src/TinyMUSH-CMake/game/db"
#define DEFAULT_LOG_HOME "/home/eddy/src/TinyMUSH-CMake/game/logs"
#define DEFAULT_MODULES_HOME "/home/eddy/src/TinyMUSH-CMake/game/modules"
#define DEFAULT_PID_HOME "/home/eddy/src/TinyMUSH-CMake/game"
#define DEFAULT_SCRIPTS_HOME "/home/eddy/src/TinyMUSH-CMake/game/scripts"
#define DEFAULT_TEXT_HOME "/home/eddy/src/TinyMUSH-CMake/game/docs"

#endif	/* __DEFAULTS_H */
