/**
 * @file config.h
 * @author TinyMUSH development team (https://github.com/TinyMUSH)
 * @brief Configuration options set by configure script
 * @version 4.0
 *
 * @copyright Copyright (C) 1989-2025 TinyMUSH development team.
 *            You may distribute under the terms the Artistic License,
 *            as specified in the COPYING file.
 *
 * @note Do not edit this file by hand -- Your changes will be overwritten
 *
 */

#ifndef __CONFIG_H
#define __CONFIG_H

#define _GNU_SOURCE

/* Maximum length of a delimiter */
#define MAX_DELIM_LEN 128

/* max # of iter levels */
#define MAX_ITER_NESTING 1024

/* Number of env vars (%0 et al) */
#define NUM_ENV_VARS 10

/* Define to the version broken down to it's components */
#define TINYMUSH_VERSION_MAJOR 4
#define TINYMUSH_VERSION_MINOR 0
#define TINYMUSH_VERSION_PATCH 0
#define TINYMUSH_VERSION_TWEAK 0

/* Define to the release status */
#define TINYMUSH_RELEASE_STATUS 0

/* Define to the version of this package. */
#define TINYMUSH_GIT_VERSION "4.0.0.0"

/* Define to the last commit date */
#define TINYMUSH_GIT_RELEASE_DATE "2026-01-05 17:11:26 +0000"

/* Define to the git hash of the last commit. */
#define TINYMUSH_GIT_HASH ""

/* 1 if source was modified since the last commit, else 0. */
#define TINYMUSH_GIT_DIRTY 0

/* Define to the build date*/
#define TINYMUSH_BUILD_DATE "2026-01-05 17:11:46"

/* Define to the authors*/
#define TINYMUSH_AUTHOR "TinyMUSH Development Team"

/* Define to the email contact*/
#define TINYMUSH_CONTACT "tinymush@googlegroups.com"

/* Define to the project copyright*/
#define TINYMUSH_COPYRIGHT "Copyright (C) TinyMUSH Development Team"

/* Define to the project license*/
#define TINYMUSH_LICENSE "Artistic License 2.0"

/* Define to the homepage url*/
#define TINYMUSH_HOMEPAGE_URL "https://github.com/TinyMUSH/"

#define DEFAULT_SHORTNAME "netmush"

#define DEFAULT_BACKUP_UTIL "/usr/bin/tar"
#define DEFAULT_BACKUP_COMPRESS "czvf"
#define DEFAULT_BACKUP_EXTRACT "xzvf"
#define DEFAULT_BACKUP_EXT "tbz"

#define DEFAULT_BACKUP_HOME "/home/runner/work/TinyMUSH/TinyMUSH/game/backups"
#define DEFAULT_BINARY_HOME "/home/runner/work/TinyMUSH/TinyMUSH/game"
#define DEFAULT_CONFIG_FILE "/home/runner/work/TinyMUSH/TinyMUSH/game/configs/netmush.conf"
#define DEFAULT_CONFIG_HOME "/home/runner/work/TinyMUSH/TinyMUSH/game/configs"
#define DEFAULT_DATABASE_HOME "/home/runner/work/TinyMUSH/TinyMUSH/game/db"
#define DEFAULT_LOG_HOME "/home/runner/work/TinyMUSH/TinyMUSH/game/logs"
#define DEFAULT_MODULES_HOME "/home/runner/work/TinyMUSH/TinyMUSH/game/modules"
#define DEFAULT_PID_HOME "/home/runner/work/TinyMUSH/TinyMUSH/game"
#define DEFAULT_SCRIPTS_HOME "/home/runner/work/TinyMUSH/TinyMUSH/game/scripts"
#define DEFAULT_TEXT_HOME "/home/runner/work/TinyMUSH/TinyMUSH/game/docs"

#endif /* __CONFIG_H */
