m4_include([libltdl/m4/argz.m4])
m4_include([libltdl/m4/libtool.m4])
m4_include([libltdl/m4/ltdl.m4])
m4_include([libltdl/m4/ltoptions.m4])
m4_include([libltdl/m4/ltsugar.m4])
m4_include([libltdl/m4/ltversion.m4])
m4_include([libltdl/m4/lt~obsolete.m4])
